### ISSUE TITLE
change port 

### ISSUE THREAD

**Issue by tonym54** [linuxserver/docker-pyload#12]
Hi . I have install this docker on my Odroid C2 with libreelec 9 and i would like to know if it possible to change port "8000" please? If yes how can i do that?

I have try to change it in web interface but it doesn't work
I have try to change it when i create docker :

docker create \
  --name=pyload \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Europe/London \
  -p 7000:7000 \
  -v /storage/downloads/pyload:/config \
  -v /var/media/Mediateque:/downloads \
  --restart unless-stopped \
  linuxserver/pyload

and it doesn't work too.

Can you help me please? 

Thanks in advance

**Comment by aptalca** [comment]
`-p 7000:8000` will do what you want

**Comment by tonym54** [comment]
It works !! Thanks a lot  :)
