### ISSUE TITLE
Project_logo url in readme-vars.yml is incorrect and logo cannot be found

### ISSUE THREAD

**Issue by technorabilia** [linuxserver/docker-pyload#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Project_logo url in readme-vars.yml should result in valid logo.

## Current Behavior
Project_logo url in readme-vars.yml is incorrect and logo cannot be found.

## Steps to Reproduce
Open the project_logo url in the browser.

## Environment
All.

## Command used to create docker container (run/create/compose/screenshot)
Does not apply.

**Comment by j0nnymoe** [comment]
![Screenshot_20210404-205255_Firefox](https://user-images.githubusercontent.com/10374553/113519977-cd27e700-9587-11eb-9e22-c0cf5a5b6e73.png)
Works fine here.

**Comment by technorabilia** [comment]
@j0nnymoe 
The problem is that you cannot hotlink this image and embed it in the lsio pages.

Error 1011 Ray ID: 63f73fb4befd1e89 • 2021-04-13 19:54:53 UTC
Access denied
What happened?
The owner of this website (pyload.net) does not allow hotlinking to that resource (/img/banner.png).
