### ISSUE TITLE
Requesting a tag for development version

### ISSUE THREAD

**Issue by dausruddin** [linuxserver/docker-pyload#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Able to use pyload with latest commit. 
I realized a [development](https://github.com/pyload/pyload/tree/develop#development-release) version with latest changes is needed after having this issue, https://github.com/pyload/pyload/issues/3957. 
Also there are fixes for filehostings which I believe only get updated into build  for every new releases?

## Current Behavior
NG version lags a few months behind and missing a lot of fixes.

## Alternatives Considered
N/A

**Comment by aptalca** [comment]
That's news to me. Last I checked, pyload-ng was deemed `alpha`.

It looks like we are installing the dev (pre-release) version as they don't even have a stable release up on pypi yet: https://pypi.org/project/pyload-ng/#history

The latest pre-release is from April 28, which is in our latest `ng` build

**Comment by dausruddin** [comment]
Oh. I was not aware. What I really want to request is to have the latest code from its Github. Is it possible?

**Comment by aptalca** [comment]
No, we're not going to build from source (their commits). Too much work for little to no gain

**Comment by dausruddin** [comment]
Okay. Thanks for replying.
