### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by yan059** [linuxserver/docker-pyload#7]
Hi ,

i've a permission denied with the plugin update manager : 
<img width="900" alt="Capture d’écran 2020-03-21 à 13 36 05" src="https://user-images.githubusercontent.com/37675697/77226551-9b5d0180-6b79-11ea-8551-59ecde2efe6f.png">
i can delete  the account & hoster  with docker exec -ti pyload bash 

but i'll redo this action every time you update the image ;-)

is it possible to take a look?

thanks a lot have a nice day

**Comment by yan059** [comment]
i forget : it's only with the "Gettwentyfourorg.py" , when i activated the debug mode the other account aren't concerned THKS

**Comment by j0nnymoe** [comment]
Please provide us with the information requested in the template.

**Comment by yan059** [comment]
invalid form
