### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by yan059** [linuxserver/docker-pyload#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Dear Sir,

Permission denied when the plugin updatemanager is running

## Expected Behavior
the script update manager will update/delete old hoster & account without issues

## Current Behavior
the script update manager is blocking on delete account & hoster GettwentyFourOrg.py
the only way is to rm the two files with docker exec -ti pyload bash, but the issues come back when the container will be updated.

## Environment
**OS: Debian10
**CPU architecture:** x86_64  

## Command used to create docker container (run/create/compose/screenshot)
docker compose
<img width="347" alt="Capture d’écran 2020-03-21 à 20 36 48" src="https://user-images.githubusercontent.com/37675697/77235165-d5e39000-6bb3-11ea-8de2-06c8e917729e.png">

## Docker logs

<img width="1206" alt="Capture d’écran 2020-03-21 à 20 39 00" src="https://user-images.githubusercontent.com/37675697/77235189-0297a780-6bb4-11ea-9e5a-0fbeb88cb1f9.png">

**Comment by yan059** [comment]
HI,

any update ? i'm only the one to have this issue?

Thanks

**Comment by r2ixuz** [comment]
Can confirm this issue.

**Comment by ghost** [comment]
Can also confirm

**Comment by XVicarious** [comment]
The files are owned by root, but the app is being run by user "abc" which is whatever you use for PUID/GID.

**Comment by yan059** [comment]
Ok But why the issue is only for this account and hooker ... 

Envoyé de mon iPhone

**Comment by ryester19** [comment]
Issue is still present

**Comment by j0nnymoe** [comment]
Would be nice if users that are experiencing this issue could provide more information other than just saying it's still an issue.

**Comment by aptalca** [comment]
Can someone test this for me?
run this on host: `docker exec -it pyload chown -R abc:abc /app/pyload`
and then try the updater and see if it works?

**Comment by ryester19** [comment]
> Would be nice if users that are experiencing this issue could provide more information other than just saying it's still an issue.

If there was any new information, I would have provided it. But it's literally the same error messages as OP even after all these months



> Can someone test this for me?
> run this on host: `docker exec -it pyload chown -R abc:abc /app/pyload`
> and then try the updater and see if it works?

Yup, that works. When a plugin is blacklisted, UpdateManager wants to delete from /app/pyload/module/plugins/, which obviously can't because everything in there is owned by root:root. For everything else, UpdateManager works in /config/userplugins/
