### ISSUE TITLE
Feature Request - Allow user to set default login

### ISSUE THREAD

**Issue by samad909** [linuxserver/docker-pyload#9]
I have a feature request which would allow the user could setup the default login (maybe as an ENV variable) instead of it having to be admin/password.

**Comment by thelamer** [comment]
The problem I have with this is we actually do a special first time setup only once to achieve this as login credentials are stored in a sqlite database on disk. 
https://github.com/linuxserver/docker-pyload/blob/master/root/etc/cont-init.d/30-config#L9-L30
I feel like anything we provide would be confusing as people would confuse it with an actual setting and try to use it to set their password down the line. 

I think our approach is all I am willing to support, the password is hard coded to this on first setup and normal users can change it in the webui on first login.

**Comment by Keridos** [comment]
Additional info. it is not possible to add users easily using the container. And it looks like the database is stored in the overlay, not the persistent volume so it probably is recreated at each update.

**Comment by thelamer** [comment]
No it is stored in the sqlite DB, it definitely survives an update `/config/files.db`
As far as adding users that is on upstream, I fail to see how we can achieve that with Docker.
